[workspace]
members = [
    "environment",
    "visualization",
    "worldgen",
    "object",
]

[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "d10ca579e43a9d072d1aa9880fa873fd59a8f0c2" }
js-sys = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "d10ca579e43a9d072d1aa9880fa873fd59a8f0c2" }
web-sys = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "d10ca579e43a9d072d1aa9880fa873fd59a8f0c2" }
