[package]
name = "myelin-visualization"
version = "0.1.0"
authors = [
    "Jan Nils Ferner <jan@myelin.ch>",
    "Mathias Fischler <mathias@myelin.ch>",
    "Ruben Schmidmeister <ruben@myelin.ch>",
    "Jeremy Stucki <jeremy@myelin.ch>",
]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "=0.2.22" }
js-sys = { version = "=0.2.6" }
myelin-environment = { path = "../environment" }
myelin-worldgen = { path = "../worldgen" }
myelin-object = { path = "../object" }


[dependencies.web-sys]
version = "0.1.0"
features = [
    "Element",
    "EventTarget",
    "HtmlElement",
    "Node",
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "EventTarget",
    "Window",
    "CssStyleDeclaration",
]

